#!/usr/bin/env bash
# Examify installer — curl|bash friendly.
#
#   curl -fsSL https://raw.githubusercontent.com/atk0309/project_Examify/main/install.sh | bash
#
# From a clone:
#   ./install.sh
#
# Non-interactive (CI / automation):
#   EXAMIFY_NONINTERACTIVE=1 SITE_URL=https://exam.example.com ./install.sh
#   Existing .env is never overwritten in non-interactive mode. Remove it first
#   to regenerate.
#
# Flags:
#   --write-env-only   write .env and exit (used by tests)
#   --skip-build       install + migrate, skip pnpm build
#   --yes              same as EXAMIFY_NONINTERACTIVE=1
set -euo pipefail

REPO_URL="${EXAMIFY_REPO_URL:-https://github.com/atk0309/project_Examify.git}"
PNPM_VERSION="${EXAMIFY_PNPM_VERSION:-10.33.0}"
MIN_NODE="22.22.2"
MAX_NODE_MAJOR=23

WRITE_ENV_ONLY=0
SKIP_BUILD=0
NONINTERACTIVE="${EXAMIFY_NONINTERACTIVE:-0}"

for arg in "$@"; do
  case "$arg" in
    --write-env-only) WRITE_ENV_ONLY=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    --yes|-y) NONINTERACTIVE=1 ;;
    --help|-h)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

prompt() {
  local var="$1"
  local message="$2"
  local default="${3-}"
  local secret="${4-}"
  local current="${!var:-}"
  if [ -n "${current}" ]; then
    return 0
  fi
  if [ "$NONINTERACTIVE" = "1" ]; then
    printf -v "$var" '%s' "$default"
    return 0
  fi
  local reply=""
  local input=/dev/tty
  if [ ! -r /dev/tty ]; then
    input=/dev/stdin
  fi
  if [ -n "$default" ]; then
    printf '%s [%s]: ' "$message" "$default" > /dev/tty 2>/dev/null || printf '%s [%s]: ' "$message" "$default"
  else
    printf '%s: ' "$message" > /dev/tty 2>/dev/null || printf '%s: ' "$message"
  fi
  if [ "$secret" = "secret" ]; then
    # shellcheck disable=SC2162
    IFS= read -rs reply < "$input" || true
    printf '\n' > /dev/tty 2>/dev/null || printf '\n'
  else
    # shellcheck disable=SC2162
    IFS= read -r reply < "$input" || true
  fi
  if [ -z "$reply" ]; then
    reply="$default"
  fi
  printf -v "$var" '%s' "$reply"
}

confirm() {
  local message="$1"
  local default="${2:-n}"
  local reply=""
  if [ "$NONINTERACTIVE" = "1" ]; then
    [ "$default" = "y" ]
    return $?
  fi
  local input=/dev/tty
  if [ ! -r /dev/tty ]; then
    input=/dev/stdin
  fi
  printf '%s [%s]: ' "$message" "$default" > /dev/tty 2>/dev/null || printf '%s [%s]: ' "$message" "$default"
  # shellcheck disable=SC2162
  IFS= read -r reply < "$input" || true
  reply="${reply:-$default}"
  case "$reply" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

rand_secret() {
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes" | tr -d '\n'
    return
  fi
  head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
}

version_ge() {
  # true if $1 >= $2 (dotted numeric)
  [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]
}

is_examify_package_json() {
  [ -f "$1" ] && grep -Eq '"name"[[:space:]]*:[[:space:]]*"project-examify"' "$1"
}

is_examify_repo() {
  is_examify_package_json package.json
}

# Walk up from $PWD until package.json name is project-examify (same marker
# as src/lib/repo-root.ts). Writes then land on the checkout `.env`, not a
# subdirectory cwd. Prints the root on stdout; returns 1 if not found.
find_examify_root() {
  local dir="$PWD"
  while :; do
    if is_examify_package_json "$dir/package.json"; then
      printf '%s\n' "$dir"
      return 0
    fi
    local parent
    parent="$(dirname "$dir")"
    if [ "$parent" = "$dir" ]; then
      return 1
    fi
    dir="$parent"
  done
}

ensure_node() {
  if ! command -v node >/dev/null 2>&1; then
    echo "Node.js ${MIN_NODE}+ is required. Install Node 22 LTS from https://nodejs.org/ and re-run." >&2
    exit 1
  fi
  local ver
  ver="$(node -p 'process.versions.node')"
  if ! version_ge "$ver" "$MIN_NODE"; then
    echo "Node.js ${ver} is too old. Examify needs ${MIN_NODE}+ (22 LTS)." >&2
    exit 1
  fi
  local major="${ver%%.*}"
  if [ "$major" -ge "$MAX_NODE_MAJOR" ]; then
    echo "Node.js ${ver} is not supported. Examify needs Node 22 LTS (${MIN_NODE}–22.x)." >&2
    exit 1
  fi
}

ensure_pnpm() {
  if command -v corepack >/dev/null 2>&1; then
    corepack enable >/dev/null 2>&1 || true
    corepack prepare "pnpm@${PNPM_VERSION}" --activate
    return
  fi
  if command -v pnpm >/dev/null 2>&1; then
    return
  fi
  echo "corepack (ships with Node) or pnpm is required." >&2
  exit 1
}

write_env() {
  local dest="${1:-.env}"
  local old_umask
  old_umask="$(umask)"
  umask 077
  {
    printf '%s\n' '# Generated by install.sh. Edit and restart the app after changes.'
    printf '\n'
    printf 'SITE_URL=%s\n' "${SITE_URL}"
    printf 'AUTH_SECRET=%s\n' "${AUTH_SECRET}"
    printf 'SETUP_BOOTSTRAP_SECRET=%s\n' "${SETUP_BOOTSTRAP_SECRET}"
    printf 'DATABASE_URL=%s\n' "${DATABASE_URL}"
    printf 'AUTH_MODE=%s\n' "${AUTH_MODE}"
    printf 'ANTHROPIC_API_KEY=%s\n' "${ANTHROPIC_API_KEY:-test}"
    if [ -n "${OPENAI_API_KEY-}" ]; then
      printf 'OPENAI_API_KEY=%s\n' "$OPENAI_API_KEY"
    fi
    printf '\n'
    printf '%s\n' '# Mail: magic-link, local-otp, and password-mode invite accept.'
    printf 'MAIL_TRANSPORT=%s\n' "${MAIL_TRANSPORT}"
  } > "$dest"

  if [ -n "${RESEND_API_KEY-}" ]; then
    printf 'RESEND_API_KEY=%s\n' "$RESEND_API_KEY" >> "$dest"
  fi
  if [ -n "${RESEND_FROM-}" ]; then
    printf 'RESEND_FROM=%s\n' "$RESEND_FROM" >> "$dest"
  fi
  if [ -n "${SMTP_HOST-}" ]; then
    {
      printf 'SMTP_HOST=%s\n' "$SMTP_HOST"
      printf 'SMTP_PORT=%s\n' "${SMTP_PORT:-587}"
      printf 'SMTP_SECURE=%s\n' "${SMTP_SECURE:-false}"
      [ -n "${SMTP_USER-}" ] && printf 'SMTP_USER=%s\n' "$SMTP_USER"
      [ -n "${SMTP_PASS-}" ] && printf 'SMTP_PASS=%s\n' "$SMTP_PASS"
      [ -n "${SMTP_FROM-}" ] && printf 'SMTP_FROM=%s\n' "$SMTP_FROM"
      [ "${SMTP_ALLOW_INSECURE-}" = "1" ] && printf 'SMTP_ALLOW_INSECURE=1\n'
    } >> "$dest"
  fi
  if [ "${ALLOW_LOCAL_OUTBOX-}" = "1" ]; then
    printf 'ALLOW_LOCAL_OUTBOX=1\n' >> "$dest"
  fi
  if [ -n "${NEXT_PUBLIC_TURNSTILE_SITE_KEY-}" ]; then
    printf 'NEXT_PUBLIC_TURNSTILE_SITE_KEY=%s\n' "$NEXT_PUBLIC_TURNSTILE_SITE_KEY" >> "$dest"
    printf 'TURNSTILE_SECRET_KEY=%s\n' "${TURNSTILE_SECRET_KEY-}" >> "$dest"
  fi
  chmod 600 "$dest"
  umask "$old_umask"
}

# --- resolve working directory ---
# Prefer the Examify checkout that contains this cwd (walk up), so `.env`
# matches env-store + examify-ingest generate even when invoked from src/.
if FOUND_ROOT="$(find_examify_root)"; then
  cd "$FOUND_ROOT"
  if [ "$WRITE_ENV_ONLY" != "1" ]; then
    echo "Using Examify checkout: $(pwd)"
  fi
elif [ "$WRITE_ENV_ONLY" = "1" ]; then
  :
else
  TARGET="${EXAMIFY_DIR:-examify}"
  if [ -d "$TARGET" ] && (cd "$TARGET" && is_examify_repo); then
    cd "$TARGET"
    echo "Using existing checkout: $(pwd)"
  else
    if ! command -v git >/dev/null 2>&1; then
      echo "git is required to clone Examify." >&2
      exit 1
    fi
    echo "Cloning ${REPO_URL} into ${TARGET}…"
    git clone --depth 1 "$REPO_URL" "$TARGET"
    cd "$TARGET"
  fi
fi

# --- collect config ---
SITE_URL="${SITE_URL:-}"
AUTH_SECRET="${AUTH_SECRET:-}"
SETUP_BOOTSTRAP_SECRET="${SETUP_BOOTSTRAP_SECRET:-}"
AUTH_MODE="${AUTH_MODE:-}"
DATABASE_URL="${DATABASE_URL:-}"
MAIL_TRANSPORT="${MAIL_TRANSPORT:-auto}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-test}"

if [ "$WRITE_ENV_ONLY" != "1" ]; then
  echo
  echo "Examify installer"
  echo "A self-hosted exam-practice app for one family. Invite-only; data stays on this box."
  echo
fi

prompt SITE_URL "Public site URL" "http://localhost:3000"
GENERATED_AUTH_SECRET=0
GENERATED_SETUP_SECRET=0
if [ -z "${AUTH_SECRET}" ]; then
  AUTH_SECRET="$(rand_secret 32)"
  GENERATED_AUTH_SECRET=1
fi
if [ -z "${SETUP_BOOTSTRAP_SECRET}" ]; then
  SETUP_BOOTSTRAP_SECRET="$(rand_secret 24)"
  GENERATED_SETUP_SECRET=1
fi
prompt DATABASE_URL "SQLite path" "file:./data/app.db"

if [ -z "${AUTH_MODE}" ]; then
  if [ "$NONINTERACTIVE" = "1" ]; then
    AUTH_MODE="password"
  else
    echo
    echo "How should people sign in?"
    echo "  1) password     — email + password; invite accept still needs mail or an outbox"
    echo "  2) magic-link   — one-time URL via Resend, SMTP, or a local outbox"
    echo "  3) local-otp    — 6-digit code written to the host outbox (tiny / LAN installs)"
    prompt AUTH_MODE_CHOICE "Choose 1, 2, or 3" "1"
    case "${AUTH_MODE_CHOICE}" in
      2|magic-link) AUTH_MODE="magic-link" ;;
      3|local-otp) AUTH_MODE="local-otp" ;;
      *) AUTH_MODE="password" ;;
    esac
  fi
fi

case "$AUTH_MODE" in
  password|magic-link|local-otp) ;;
  *)
    echo "AUTH_MODE must be password, magic-link, or local-otp." >&2
    exit 1
    ;;
esac

if [ "$AUTH_MODE" != "password" ] && [ "$NONINTERACTIVE" != "1" ]; then
  echo
  echo "Email delivery for ${AUTH_MODE}:"
  echo "  1) none / local outbox  (dev, or prod with ALLOW_LOCAL_OUTBOX=1)"
  echo "  2) Resend"
  echo "  3) SMTP"
  prompt MAIL_CHOICE "Choose 1, 2, or 3" "1"
  case "${MAIL_CHOICE}" in
    2|resend)
      MAIL_TRANSPORT="resend"
      prompt RESEND_API_KEY "Resend API key" "" secret
      prompt RESEND_FROM "Resend From: address (Name <you@domain>)"
      ;;
    3|smtp)
      MAIL_TRANSPORT="smtp"
      prompt SMTP_HOST "SMTP host"
      prompt SMTP_PORT "SMTP port" "587"
      prompt SMTP_USER "SMTP username" ""
      prompt SMTP_PASS "SMTP password" "" secret
      prompt SMTP_FROM "SMTP From: address"
      ;;
    *)
      MAIL_TRANSPORT="outbox"
      if [ "$AUTH_MODE" = "local-otp" ] || confirm "Allow writing sign-in tokens to a local outbox in production?" "n"; then
        ALLOW_LOCAL_OUTBOX=1
      fi
      ;;
  esac
fi

if [ "$AUTH_MODE" = "local-otp" ] && [ "${ALLOW_LOCAL_OUTBOX-}" != "1" ]; then
  ALLOW_LOCAL_OUTBOX=1
fi

if [ "$NONINTERACTIVE" != "1" ] && confirm "Enable Cloudflare Turnstile (captcha)?" "n"; then
  prompt NEXT_PUBLIC_TURNSTILE_SITE_KEY "Turnstile site key"
  prompt TURNSTILE_SECRET_KEY "Turnstile secret key" "" secret
fi

if [ "$NONINTERACTIVE" != "1" ]; then
  echo
  echo "Optional: OPENAI_API_KEY for /onboarding Cloud (OpenAI) generate."
  echo "Same .env store as the wizard. Leave blank to skip (you can set it later)."
  prompt OPENAI_API_KEY "OpenAI API key" "" secret
fi

WROTE_ENV=0
KEPT_EXISTING_ENV=0
if [ -f .env ]; then
  if [ "$NONINTERACTIVE" = "1" ]; then
    echo "Keeping existing .env (non-interactive; not overwriting)."
    KEPT_EXISTING_ENV=1
  elif ! confirm ".env already exists. Overwrite?" "n"; then
    echo "Keeping existing .env"
    KEPT_EXISTING_ENV=1
  else
    write_env .env
    WROTE_ENV=1
    echo "Wrote .env"
  fi
else
  write_env .env
  WROTE_ENV=1
  echo "Wrote .env"
fi

if [ "$WROTE_ENV" = "1" ] && [ "$NONINTERACTIVE" != "1" ]; then
  if [ "$GENERATED_AUTH_SECRET" = "1" ]; then
    echo "Generated AUTH_SECRET."
  fi
  if [ "$GENERATED_SETUP_SECRET" = "1" ]; then
    echo "Generated SETUP_BOOTSTRAP_SECRET (you will type this at /setup)."
    echo "  ${SETUP_BOOTSTRAP_SECRET}"
  fi
fi

if [ "$WRITE_ENV_ONLY" = "1" ]; then
  exit 0
fi

ensure_node
ensure_pnpm

echo
echo "Installing dependencies…"
pnpm install --frozen-lockfile

echo "Applying database migrations…"
pnpm db:migrate

if [ "$SKIP_BUILD" != "1" ]; then
  echo "Building production app…"
  pnpm build
fi

echo
echo "Examify is ready."
echo
if [ "$KEPT_EXISTING_ENV" = "1" ]; then
  echo "Using the existing .env. Start with: pnpm start   (or: pnpm dev)"
  echo "Open the SITE_URL from that file. This run's generated setup code was not written."
else
  echo "  1. Start the server:   pnpm start          (or: pnpm dev)"
  echo "  2. Open SITE_URL:      ${SITE_URL}"
  echo "  3. First run:          ${SITE_URL%/}/setup"
  echo "     Setup code:         ${SETUP_BOOTSTRAP_SECRET}"
  echo "     Auth mode:          ${AUTH_MODE}"
  echo
  echo "Invite family from the parent dashboard after setup."
  echo "Edit .env and restart to change AUTH_MODE, mail, or Turnstile."
  echo
  if [ "$AUTH_MODE" = "local-otp" ] || [ "${MAIL_TRANSPORT}" = "outbox" ]; then
    echo "Local outbox path: data/outbox (or MAIL_OUTBOX_DIR). Treat it as secret."
  fi
fi
